/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Yasmin
 */
public class TelaCalculo extends javax.swing.JFrame {

    /**
     * Creates new form TelaTempoVida
     */
    public TelaCalculo() {
        initComponents();
        lblResultado.setVisible(false);
        lblAnosPerdidos.setVisible(false);
        lblGasto.setVisible(false);
        lblGastoAnu.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtDias = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtAnos = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();
        lblAnosPerdidos = new javax.swing.JLabel();
        lblGasto = new javax.swing.JLabel();
        lblGastoAnu = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Quantos cigarros você fuma por dia?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, -1));

        txtDias.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtDias, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 11, 73, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Quantos anos você já fumou?");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 72, -1, -1));

        txtAnos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtAnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 69, 133, -1));

        btnCalcular.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 122, -1, -1));

        lblResultado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblResultado.setForeground(new java.awt.Color(255, 255, 102));
        lblResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultado.setText("Tempo de vida");
        getContentPane().add(lblResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 349, -1));

        lblAnosPerdidos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAnosPerdidos.setForeground(new java.awt.Color(255, 204, 102));
        lblAnosPerdidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAnosPerdidos.setText("Anos de vida perdido");
        getContentPane().add(lblAnosPerdidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 349, -1));

        lblGasto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblGasto.setForeground(new java.awt.Color(255, 255, 102));
        lblGasto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGasto.setText("Gasto com Cigarro");
        getContentPane().add(lblGasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 349, -1));

        lblGastoAnu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblGastoAnu.setForeground(new java.awt.Color(255, 204, 102));
        lblGastoAnu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGastoAnu.setText("Gasto anual com cigarro");
        getContentPane().add(lblGastoAnu, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 290, 350, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cigarro.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        int qtdC = Integer.parseInt(txtDias.getText());
        int a = Integer.parseInt(txtAnos.getText());
        
        int tC = (a*365)* qtdC;
        int dP = (tC * 10)/24;
        int aP = dP/365;
        double gC = (qtdC*7)*30;
        double gCA = (a*365)*7;
        
        lblResultado.setText("Você perdeu "+dP+" dias de vida!");
        lblAnosPerdidos.setText("Isso dá "+aP+" anos de vida perdidos!");
        lblGasto.setText(String.format("Por mês você gasta %.2fR$!", gC));
        lblGastoAnu.setText(String.format("Foram %.2fR$ gastos nesses %s anos!", gCA,a));
        
        lblResultado.setVisible(true);
        lblAnosPerdidos.setVisible(true);
        lblGasto.setVisible(true);
        lblGastoAnu.setVisible(true);
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCalculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCalculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCalculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCalculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCalculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblAnosPerdidos;
    private javax.swing.JLabel lblGasto;
    private javax.swing.JLabel lblGastoAnu;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JTextField txtAnos;
    private javax.swing.JTextField txtDias;
    // End of variables declaration//GEN-END:variables
}
