package com.cursoemvideo.soma;

/**
 *
 * @author Yasmin
 */
public class TelaSoma extends javax.swing.JFrame {

    /**
     * Creates new form TelaSoma
     */
    public TelaSoma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtN1 = new javax.swing.JTextField();
        txtN2 = new javax.swing.JTextField();
        txtN3 = new javax.swing.JTextField();
        txtN4 = new javax.swing.JTextField();
        txtN5 = new javax.swing.JTextField();
        txtN6 = new javax.swing.JTextField();
        txtN7 = new javax.swing.JTextField();
        txtN8 = new javax.swing.JTextField();
        lblSoma = new javax.swing.JLabel();
        lblSubtracao = new javax.swing.JLabel();
        lblMultiplicacao = new javax.swing.JLabel();
        lblDivisao = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSoma = new javax.swing.JButton();
        btnSubtracao = new javax.swing.JButton();
        btnMultiplicacao = new javax.swing.JButton();
        btnDivisao = new javax.swing.JButton();
        lblQuadroNegro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtN1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(txtN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 70, 40));

        txtN2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(txtN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 70, 40));

        txtN3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(txtN3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 70, 40));

        txtN4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(txtN4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 70, 40));

        txtN5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(txtN5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 70, 40));

        txtN6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(txtN6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 70, 40));

        txtN7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(txtN7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 70, 40));

        txtN8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(txtN8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 70, 40));

        lblSoma.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblSoma.setForeground(new java.awt.Color(255, 255, 255));
        lblSoma.setText("0");
        getContentPane().add(lblSoma, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 50, 40));

        lblSubtracao.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblSubtracao.setForeground(new java.awt.Color(255, 255, 255));
        lblSubtracao.setText("0");
        getContentPane().add(lblSubtracao, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 148, 50, 40));

        lblMultiplicacao.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblMultiplicacao.setForeground(new java.awt.Color(255, 255, 255));
        lblMultiplicacao.setText("0");
        getContentPane().add(lblMultiplicacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 248, 50, 40));

        lblDivisao.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblDivisao.setForeground(new java.awt.Color(255, 255, 255));
        lblDivisao.setText("0");
        getContentPane().add(lblDivisao, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 100, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("+");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 20, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("-");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("X");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("/");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, -1, -1));

        btnSoma.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSoma.setText("=");
        btnSoma.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        btnSoma.setMinimumSize(new java.awt.Dimension(6, 20));
        btnSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSomaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSoma, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 70, 40));

        btnSubtracao.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSubtracao.setText("=");
        btnSubtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubtracaoActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubtracao, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 70, 40));

        btnMultiplicacao.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMultiplicacao.setText("=");
        btnMultiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicacaoActionPerformed(evt);
            }
        });
        getContentPane().add(btnMultiplicacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 70, 40));

        btnDivisao.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDivisao.setText("=");
        btnDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivisaoActionPerformed(evt);
            }
        });
        getContentPane().add(btnDivisao, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 70, 40));

        lblQuadroNegro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cursoemvideo/soma/fundo-do-quadro-negro_87498-397.jpg"))); // NOI18N
        getContentPane().add(lblQuadroNegro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSomaActionPerformed
        int n1 = Integer.parseInt(txtN1.getText());
        int n2 = Integer.parseInt(txtN2.getText());
        int soma = n1 + n2;
        //Exibindo o valor no label soma transformando o valor int 's' para 
        //string 
        lblSoma.setText(Integer.toString(soma));
    }//GEN-LAST:event_btnSomaActionPerformed

    private void btnSubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubtracaoActionPerformed
        int n1 = Integer.parseInt(txtN3.getText());
        int n2 = Integer.parseInt(txtN4.getText());
        int subtracao = n1 - n2;
        lblSubtracao.setText(Integer.toString(subtracao));
    }//GEN-LAST:event_btnSubtracaoActionPerformed

    private void btnMultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicacaoActionPerformed
        int n1 = Integer.parseInt(txtN5.getText());
        int n2 = Integer.parseInt(txtN6.getText());
        int multiplicacao = n1 * n2;
        lblMultiplicacao.setText(Integer.toString(multiplicacao));
    }//GEN-LAST:event_btnMultiplicacaoActionPerformed

    private void btnDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivisaoActionPerformed
        float n1 = Float.parseFloat(txtN7.getText());
        float n2 = Float.parseFloat(txtN8.getText());
        float divisao = n1 / n2;
        lblDivisao.setText(Float.toString(divisao));
    }//GEN-LAST:event_btnDivisaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSoma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSoma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSoma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSoma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSoma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDivisao;
    private javax.swing.JButton btnMultiplicacao;
    private javax.swing.JButton btnSoma;
    private javax.swing.JButton btnSubtracao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblDivisao;
    private javax.swing.JLabel lblMultiplicacao;
    private javax.swing.JLabel lblQuadroNegro;
    private javax.swing.JLabel lblSoma;
    private javax.swing.JLabel lblSubtracao;
    private javax.swing.JTextField txtN1;
    private javax.swing.JTextField txtN2;
    private javax.swing.JTextField txtN3;
    private javax.swing.JTextField txtN4;
    private javax.swing.JTextField txtN5;
    private javax.swing.JTextField txtN6;
    private javax.swing.JTextField txtN7;
    private javax.swing.JTextField txtN8;
    // End of variables declaration//GEN-END:variables
}
